Repository 2023-HATCH/hatch-flutter-app-2023, pull requests merged in 2023-06, with the labels that each got.

#4 [feat] 스테이지: 노래 재생 기능 추가HH-168)
  lib/config/audio_player/audio_player_util.dart
  lib/ui/view/ml_kit_camera_view.dart
  lib/ui/view/ml_kit_pose_detector_view.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
Labels: feat

#5 [Feat] 화면에 보이는 스켈레톤을 커스텀 (HH-171)
  assets/images/info_images.dart
  lib/config/app_color.dart
  lib/config/ml_kit/custom_pose_painter.dart
  lib/ui/screen/profile_screen.dart
  lib/ui/view/skeleton_custom_view.dart
  pubspec.lock
  pubspec.yaml
Labels: feat

#6 [rename]스켈레톤 커스텀 코드 병합(HH-171)
  lib/config/ml_kit/pose_painter.dart
  lib/ui/screen/popo_screen.dart
  lib/ui/screen/profile_screen.dart
  lib/ui/view/ml_kit_pose_detector_view.dart
  lib/ui/view/ml_kit_skeleton_custom_view.dart
  pubspec.yaml
Labels: rename, remove

#7 [feat] 홈 화면 UI 개발 (HH-176)
  assets/font/info_font.dart
  assets/fonts/GmarketSansTTFBold.ttf
  assets/fonts/GmarketSansTTFLight.ttf
  assets/fonts/GmarketSansTTFMedium.ttf
  assets/icons/home_chat.svg
  assets/icons/home_like.svg
  assets/icons/home_popo.svg
  assets/icons/home_profile.svg
  assets/icons/home_progress.svg
  assets/icons/home_search.svg
  assets/icons/home_share.svg
  assets/icons/home_upload.svg
  assets/images/home_profile_1.jpg
  assets/images/home_profile_2.jpg
  assets/images/home_profile_3.jpg
  assets/images/home_profile_4.jpg
  assets/images/home_profile_5.jpg
  lib/main.dart
  lib/ui/screen/home_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: feat, design, ui

#9 [bug] #7 이후 홈 화면 오류 수정 및 비디오 재생 기능 보완(HH-176)
  lib/data/local/provider/info_local_provider.dart
  lib/data/local/provider/video_play_provider.dart
  lib/main.dart
  lib/ui/screen/home_screen.dart
  lib/ui/screen/main_screen.dart
  lib/ui/screen/popo_result_screen.dart
  lib/ui/screen/popo_wait_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: feat, bug, comment

#10 [comment/refactor] #9 에서 개발한 홈화면 코드 정리(HH-176)
  lib/data/local/provider/video_play_provider.dart
  lib/ui/screen/home_screen.dart
  lib/ui/screen/main_screen.dart
  lib/ui/screen/popo_wait_screen.dart
  lib/ui/view/ml_kit_camera_view.dart
  lib/ui/widget/home_video_frame_content_widget.dart
  lib/ui/widget/home_video_frame_header_widget.dart
  lib/ui/widget/home_video_frame_right_widget.dart
Labels: refactor, comment

#12 [!HOTFIX] 포포 스테이지 시연용 개발 완료(머지 오류 해결)(HH-177)
  android/app/src/main/AndroidManifest.xml
  assets/icons/ic_home.svg
  assets/icons/ic_music_note_big.svg
  assets/icons/ic_users.svg
  assets/images/bg_popo_result.png
  assets/images/charactor_popo_catch.svg
  assets/images/charactor_popo_wait.svg
  ios/Runner/Info.plist
  lib/config/audio_player/audio_player_util.dart
  lib/ui/screen/main_screen.dart
  lib/ui/screen/popo_catch_screen.dart
  lib/ui/screen/popo_play_screen.dart
  lib/ui/screen/popo_result_screen.dart
  lib/ui/screen/popo_stage_screen.dart
  lib/ui/screen/popo_wait_screen.dart
  lib/ui/view/ml_kit_camera_view.dart
  lib/ui/view/popo_catch_view.dart
  lib/ui/view/popo_play_view.dart
  lib/ui/view/popo_result_view.dart
  lib/ui/view/popo_wait_view.dart
  pubspec.lock
Labels: !HOTFIX

#14 [Bug] 포포에서 홈으로 돌아왔을 때 영상 다시 재생 안 되는 문제 해결 (HH-176)
  lib/ui/screen/popo_stage_screen.dart
Labels: bug

#15 [chore] 앱 로고 추가(HH-178)
  android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  assets/images/app_logo.png
  flutter_launcher_icons.yaml
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-1024x1024@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-20x20@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-29x29@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-40x40@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-50x50@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-50x50@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-57x57@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-57x57@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-60x60@3x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-72x72@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-72x72@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@1x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-76x76@2x.png
  ios/Runner/Assets.xcassets/AppIcon.appiconset/Icon-App-83.5x83.5@2x.png
  pubspec.lock
  pubspec.yaml
Labels: chore

#16 [feat] 시연을 위한 포포 스테이지 추가 기능 구현(HH-179)
  assets/icons/ic_music_note_small.svg
  lib/ui/screen/popo_stage_screen.dart
  lib/ui/view/ml_kit_camera_view.dart
  lib/ui/view/popo_catch_view.dart
  pubspec.lock
  pubspec.yaml
Labels: feat

#18 [feat] 홈 화면에서 스크롤 시 깜빡임 없앰 (HH-176)
  lib/ui/screen/home_screen.dart
Labels: feat

#19 [feat] 포포 스테이지 플레이 화면 전에 스켈레톤 추출 기능 추가(HH-181)
  lib/config/audio_player/audio_player_util.dart
  lib/ui/view/ml_kit_camera_view.dart
  lib/ui/view/popo_play_view.dart
  lib/ui/view/popo_result_view.dart
  pubspec.lock
Labels: feat

#20 [refactor] 홈 화면 처음에만 포포 스피너 보이기, 하단 위젯 위치(HH-176)
  assets/icons/ic_dancing_popo.svg
  lib/data/local/provider/video_play_provider.dart
  lib/ui/screen/home_screen.dart
  lib/ui/widget/dancing_popo_widget.dart
  lib/ui/widget/home_video_frame_content_widget.dart
  lib/ui/widget/home_video_frame_right_widget.dart
  pubspec.lock
  pubspec.yaml
Labels: refactor

#21 [feat] Profile Screen 에서 카카오 로그인 후 토큰 받아와서 사용자 정보 확인 (HH-172)
  android/app/build.gradle
  android/app/src/debug/AndroidManifest.xml
  android/app/src/main/AndroidManifest.xml
  android/app/src/main/kotlin/com/example/pocketpose/MainActivity.kt
  android/app/src/profile/AndroidManifest.xml
  assets/icons/ic_exit.svg
  assets/images/kakao_login.png
  assets/images/kakao_login_popo.svg
  assets/images/kakao_logo.png
  ios/Runner/Info.plist
  lib/domain/enum/login_platform.dart
  lib/domain/provider/auth_provider.dart
  lib/main.dart
  lib/ui/screen/main_screen.dart
  lib/ui/screen/profile_screen.dart
  lib/ui/widget/login_modal_content_widget.dart
  lib/ui/widget/not_login_widget.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: feat, design, ui

#22 [UI] 프로필 화면 UI 완성 및 기타 작업 (HH-218)
  assets/icons/home_popo.svg
  assets/icons/home_profile.svg
  assets/icons/ic_bottom_popo.svg
  assets/icons/ic_home_chat.svg
  assets/icons/ic_home_like.svg
  assets/icons/ic_home_progress.svg
  assets/icons/ic_home_search.svg
  assets/icons/ic_home_share.svg
  assets/icons/ic_home_upload.svg
  assets/icons/ic_profile_edit.svg
  assets/icons/ic_profile_heart_select.svg
  assets/icons/ic_profile_heart_unselect.svg
  assets/icons/ic_profile_insta.svg
  assets/icons/ic_profile_list_select.svg
  assets/icons/ic_profile_list_unselect.svg
  assets/icons/ic_profile_setting.svg
  assets/icons/ic_spinner.png
  assets/images/profile_profile.png
  assets/images/profile_video_0.png
  assets/images/profile_video_1.png
  assets/images/profile_video_10.png
  assets/images/profile_video_11.png
  assets/images/profile_video_2.png
  assets/images/profile_video_3.png
  assets/images/profile_video_4.png
  assets/images/profile_video_5.png
  assets/images/profile_video_6.png
  assets/images/profile_video_7.png
  assets/images/profile_video_8.png
  assets/images/profile_video_9.png
  lib/config/app_color.dart
  lib/data/local/provider/auth_provider.dart
  lib/main.dart
  lib/ui/screen/NestedScrollViewExample.dart
  lib/ui/screen/home_screen.dart
  lib/ui/screen/main_screen.dart
  lib/ui/screen/profile_screen.dart
  lib/ui/widget/home/home_video_frame_content_widget.dart
  lib/ui/widget/home/home_video_frame_right_widget.dart
  lib/ui/widget/home_video_frame_header_widget.dart
  lib/ui/widget/login_modal_content_widget.dart
  lib/ui/widget/music_spinner_widget.dart
  lib/ui/widget/profile/profile_infomation_widget.dart
Labels: feat, ui, rename, remove

#24 [feat]온보딩 화면 추가(HH-223)
  assets/icons/ic_left_purple.svg
  assets/icons/ic_right_purple.svg
  assets/images/charactor_on_boarding.svg
  lib/config/app_color.dart
  lib/config/audio_player/audio_player_util.dart
  lib/config/ml_kit/custom_pose_painter.dart
  lib/data/local/provider/local_pref_provider.dart
  lib/data/local/provider/video_play_provider.dart
  lib/main.dart
  lib/ui/screen/on_boarding_screen.dart
  lib/ui/screen/popo_stage_screen.dart
  lib/ui/view/ml_kit_camera_view.dart
  lib/ui/view/popo_catch_view.dart
  pubspec.lock
  pubspec.yaml
  test/widget_test.dart
Labels: feat, ui

#26 [feat] 포포스테이지 불꽃 반응 애니메이션 기능 구현 (HH-230)
  assets/icons/ic_popo_fire_select.png
  assets/icons/ic_popo_fire_unselect.svg
  lib/ui/screen/profile/profile_edit_screen.dart
  lib/ui/screen/profile/profile_screen.dart
Labels: feat

#27 [feat] 커뮤니티 화면의 좋아요 아이콘 애니메이션 추가 (HH-176)
  assets/icons/ic_heart_select.svg
  assets/icons/ic_heart_unselect.svg
  assets/icons/ic_home_heart_unselect.svg
  lib/ui/screen/profile/profile_screen.dart
  lib/ui/widget/home/home_video_frame_right_widget.dart
Labels: feat

#28 [ui] 스테이지 ui 개발(HH-227)
  .vscode/launch.json
  android/app/src/main/AndroidManifest.xml
  assets/icons/ic_stage_back_white.svg
  assets/images/img_stage_result_mvp.svg
  lib/config/app_color.dart
  lib/data/local/provider/video_play_provider.dart
  lib/ui/screen/on_boarding_screen.dart
  lib/ui/screen/popo_stage_screen.dart
  lib/ui/view/popo_catch_view.dart
  lib/ui/view/popo_play_view.dart
  lib/ui/view/popo_result_view.dart
Labels: ui

#29 [ui] 스테이지 사용자 목록 다이얼로그 개발 (HH-233)
  lib/data/entity/response/stage_user_list_response.dart
  lib/data/entity/response/stage_user_list_response.g.dart
  lib/domain/entity/stage_user_list_item.dart
  lib/domain/entity/stage_user_list_item.g.dart
  lib/ui/screen/popo_stage_screen.dart
  lib/ui/view/ml_kit_camera_view.dart
Labels: ui

#31 [feat] 커뮤니티 좋아요 아이콘 애니메이션 수정 (HH-176)
  lib/data/local/provider/video_play_provider.dart
  lib/ui/widget/home/home_video_frame_right_widget.dart
  pubspec.lock
  pubspec.yaml
Labels: feat, ui
