Repository 2023-HATCH/hatch-flutter-app-2023, pull requests merged in 2023-09, with the labels that each got.

#103 [refactor] PROBLEMS 모두 해결, [fix] 팔로우 페이지 자기소개 null 값 오류 해결
  lib/data/entity/response/stage_user_list_response.g.dart
  lib/data/remote/provider/kakao_login_provider.dart
  lib/data/remote/provider/profile_provider.dart
  lib/data/remote/provider/search_provider.dart
  lib/data/remote/repository/search_repository.dart
  lib/domain/entity/follow_data.dart
  lib/domain/entity/follow_data.g.dart
  lib/domain/entity/user_list_item.g.dart
  lib/ui/loader/upload_spinner_loader.dart
  lib/ui/screen/profile/follow_tab_screen.dart
  lib/ui/screen/profile/profile_edit_screen.dart
  lib/ui/screen/profile/profile_setting_screen.dart
  lib/ui/screen/profile/profile_video_detail_screen.dart
  lib/ui/view/home/comment_button_view.dart
  lib/ui/view/home/search_detail_view.dart
  lib/ui/view/home/user_list_view.dart
  lib/ui/view/profile/follow_user_list_view.dart
  lib/ui/view/profile/profile_buttons_view.dart
  lib/ui/view/profile/profile_tab_videos_view.dart
  lib/ui/view/video/multi_video_player_view.dart
  lib/ui/view/video/video_right_view.dart
  lib/ui/widget/home/upload_button_widget.dart
  lib/ui/widget/video/share_button_widget.dart
  lib/ui/widget/video/video_player_widget.dart
  pubspec.lock
Labels: fix, refactor

#104 [feat] 카카오 공유 기능 추가 (HH-407)
  android/app/src/main/AndroidManifest.xml
  ios/Runner/Info.plist
  lib/config/firebase/dynamic_link_util.dart
  lib/config/firebase/i_dynamic_link.dart
  lib/config/share/dynamic_link.dart
  lib/config/share/kakao_link_with_dynamic_link.dart
  lib/data/entity/response/stage_user_list_response.g.dart
  lib/domain/entity/follow_data.g.dart
  lib/domain/entity/user_list_item.g.dart
  lib/main.dart
  lib/ui/screen/main_screen.dart
  lib/ui/widget/video/share_button_widget.dart
  pubspec.lock
  pubspec.yaml
Labels: feat

#105 [feat] 영상 상세 api 연결 (HH-410)
  lib/data/entity/response/share_response.dart
  lib/data/entity/response/share_response.g.dart
  lib/data/remote/provider/share_provider_impl.dart
  lib/data/remote/repository/share_repository_impl.dart
  lib/domain/provider/share_provider.dart
  lib/domain/repository/share_repository.dart
  lib/main.dart
  lib/ui/screen/share_screen.dart
Labels: feat

#106 [feat] 프로필 화면 생성 기능 개발 (HH-323)
  lib/data/local/provider/multi_video_play_provider.dart
  lib/data/remote/provider/profile_provider.dart
  lib/domain/entity/follow_data.g.dart
  lib/domain/entity/search_user_data.g.dart
  lib/ui/loader/profile_video_skeleton_loader.dart
  lib/ui/screen/profile/profile_screen.dart
  lib/ui/view/home/comment_button_view.dart
  lib/ui/view/home/search_detail_view.dart
  lib/ui/view/home/search_view.dart
  lib/ui/view/home/user_list_view.dart
  lib/ui/view/profile/profile_tab_videos_view.dart
  lib/ui/view/video/video_user_info_view.dart
  lib/ui/widget/video/video_player_widget.dart
  pubspec.lock
  windows/runner/flutter_window.cpp
Labels: feat

#108 [feat] 채팅 백그라운드/포그라운드 푸시 알림 + 리다이렉션 개발 (HH-411)
  android/app/src/main/AndroidManifest.xml
  lib/config/fcm/notification_service.dart
  lib/config/fcm/remote_notifications_ervice.dart
  lib/config/share/kakao_link_with_dynamic_link.dart
  lib/data/remote/repository/chat_repository_impl.dart
  lib/data/remote/repository/stage_repository_impl.dart
  lib/data/remote/repository/stage_talk_repository_impl.dart
  lib/data/remote/repository/video_upload_repository_impl.dart
  lib/main.dart
  lib/ui/screen/chat/chat_detail_screen.dart
  lib/ui/screen/chat/chat_room_list_screen.dart
  lib/ui/widget/chat/chat_room_list_item_widget.dart
  lib/ui/widget/chat/chat_search_user_list_item_widget.dart
Labels: feat

#109 [feat] 포포 입장 음 변경(HH-425), [feat] 드래그 해서 pop 기능 개발 (HH-426)
  assets/audios/sound_popo_click.mp3
  lib/ui/screen/chat/chat_detail_screen.dart
  lib/ui/screen/chat/chat_room_list_screen.dart
  lib/ui/screen/home/home_screen.dart
  lib/ui/screen/home/home_search_screen.dart
  lib/ui/screen/main_screen.dart
  lib/ui/screen/popo_stage_screen.dart
  lib/ui/screen/profile/follow_tab_screen.dart
  lib/ui/screen/profile/profile_edit_screen.dart
  lib/ui/screen/profile/profile_screen.dart
  lib/ui/screen/profile/profile_setting_screen.dart
  lib/ui/screen/profile/profile_video_detail_screen.dart
  lib/ui/view/profile/profile_buttons_view.dart
  lib/ui/view/video/video_user_info_view.dart
Labels: feat

#110 [feat] 댓글 푸시 알림 기능 개발 (HH-427)
  lib/ui/screen/main_screen.dart
  lib/ui/screen/profile/profile_screen.dart
  lib/ui/screen/share_screen.dart
  lib/ui/widget/profile/profile_tapbar_widget.dart
Labels: feat

#111 [refactor/HOTFIX] 스테이지 소켓 최적화 (HH-409)
  assets/images/bg_popo_wait.png
  lib/data/remote/provider/socket_stage_provider_impl.dart
  lib/data/remote/provider/stage_provider_impl.dart
  lib/ui/screen/main_screen.dart
  lib/ui/screen/popo_stage_screen.dart
  lib/ui/view/stage/ml_kit_camera_play_view.dart
  lib/ui/view/stage/ml_kit_camera_result_view.dart
  lib/ui/view/stage/popo_catch_view.dart
  lib/ui/view/stage/popo_play_view.dart
  lib/ui/view/stage/popo_result_view.dart
  lib/ui/view/stage/popo_wait_view.dart
  lib/ui/widget/stage/stage_catch_music_info_widget.dart
  lib/ui/widget/stage/stage_catch_progressbar_widget.dart
  lib/ui/widget/stage/stage_live_chat_bar_widget.dart
  lib/ui/widget/stage/stage_live_talk_list_widget.dart
Labels: !HOTFIX, refactor

#112 [refactor] 스테이지 최적화(플레이, 결과 camera view rebuild 최적화) + 중간입장 처리 (HH-409)
  lib/data/remote/provider/socket_stage_provider_impl.dart
  lib/data/remote/provider/stage_provider_impl.dart
  lib/ui/screen/popo_stage_screen.dart
  lib/ui/screen/share_screen.dart
  lib/ui/view/stage/ml_kit_camera_play_view.dart
  lib/ui/view/stage/ml_kit_camera_result_view.dart
  lib/ui/view/stage/popo_catch_view.dart
  lib/ui/view/stage/popo_play_view.dart
  lib/ui/view/stage/popo_result_view.dart
  lib/ui/widget/chat/chat_detail_left_bubble_widget.dart
  lib/ui/widget/stage/stage_appbar_music_info_widget.dart
  lib/ui/widget/stage/stage_live_talk_list_widget.dart
  lib/ui/widget/stage/stage_play_countdown_widget.dart
Labels: refactor

#115 [feat] 스테이지 중간 점수 연결 및 배경 전환 오류 수정 (HH-419)
  lib/data/entity/socket_response/stage_mid_score_response.dart
  lib/data/entity/socket_response/stage_mid_score_response.g.dart
  lib/data/remote/provider/socket_stage_provider_impl.dart
  lib/ui/screen/stage/popo_stage_screen.dart
  lib/ui/view/stage/popo_play_view.dart
  pubspec.lock
Labels: feat

#116 [fix] 온보딩 사진 변경 및 사이즈 에러 수정 + 채팅 목록 프로필 로딩 에러 수정 (HH-437)
  assets/images/img_onboarding_catch.jpeg
  assets/images/img_onboarding_play.jpeg
  assets/images/img_onboarding_result.jpeg
  assets/images/img_onboarding_wait.jpeg
  lib/ui/screen/onboarding/on_boarding_screen.dart
  lib/ui/widget/chat/chat_room_list_item_widget.dart
Labels: fix

#117 [feat] 포포 스테이지 녹화 기능 보완 (HH-414)
  lib/ui/screen/stage/popo_stage_screen.dart
  lib/ui/view/home/comment_button_view.dart
  lib/ui/widget/video/video_upload_dialog.dart
Labels: feat

#119 [ui] 스테이지 mvp ui 변경 (HH-441)
  assets/images/img_stage_result_1.svg
  assets/images/img_stage_result_2.svg
  assets/images/img_stage_result_3.svg
  lib/data/remote/provider/socket_stage_provider_impl.dart
  lib/ui/screen/stage/popo_stage_screen.dart
  lib/ui/view/stage/ml_kit_camera_result_view.dart
  lib/ui/view/stage/popo_play_view.dart
  lib/ui/view/stage/popo_result_view.dart
  lib/ui/widget/stage/stage_catch_progressbar_widget.dart
  lib/ui/widget/stage/stage_live_talk_list_widget.dart
  lib/ui/widget/stage/stage_result_player_info_widget.dart
Labels: fix, ui

#120 [feat] 기능 보완 - 로그아웃, 프로필, 검색 (HH-450)
  lib/data/remote/provider/kakao_login_provider.dart
  lib/ui/loader/profile_screen_loader.dart
  lib/ui/loader/profile_video_skeleton_loader.dart
  lib/ui/screen/profile/profile_screen.dart
  lib/ui/screen/profile/profile_video_detail_screen.dart
  lib/ui/view/profile/profile_tab_videos_view.dart
  lib/ui/view/profile/profile_user_info_view.dart
  lib/ui/view/video/video_user_info_view.dart
Labels: feat

#121 [fix] #120 이후 프로필 MediaCodecVideoRenderer error 해결 (HH-458)
  lib/ui/view/profile/profile_tab_videos_view.dart
  lib/ui/widget/home/search_textfield_widget.dart
Labels: fix

#122 [Refactor] 서연 모든 코드 리팩토링 (HH-452)
  lib/data/local/provider/multi_video_play_provider.dart
  lib/data/remote/provider/comment_provider.dart
  lib/data/remote/provider/follow_provider.dart
  lib/data/remote/provider/kakao_login_provider.dart
  lib/data/remote/provider/like_provider.dart
  lib/data/remote/provider/profile_provider.dart
  lib/data/remote/provider/search_provider.dart
  lib/data/remote/provider/video_provider.dart
  lib/data/remote/repository/comment_repository.dart
  lib/data/remote/repository/follow_repository.dart
  lib/data/remote/repository/kakao_login_repository.dart
  lib/data/remote/repository/like_repository.dart
  lib/data/remote/repository/profile_repository.dart
  lib/data/remote/repository/search_repository.dart
  lib/data/remote/repository/share_repository_impl.dart
  lib/data/remote/repository/video_repository.dart
  lib/ui/screen/home/home_screen.dart
  lib/ui/screen/home/home_search_screen.dart
  lib/ui/screen/profile/follow_tab_screen.dart
  lib/ui/screen/profile/profile_edit_screen.dart
  lib/ui/screen/profile/profile_screen.dart
  lib/ui/screen/profile/profile_setting_screen.dart
  lib/ui/screen/profile/profile_video_detail_screen.dart
  lib/ui/screen/video/video_detail_screen.dart
  lib/ui/view/home/comment_button_view.dart
  lib/ui/view/home/search_detail_view.dart
  lib/ui/view/home/search_view.dart
  lib/ui/view/profile/profile_buttons_view.dart
  lib/ui/view/profile/profile_tab_videos_view.dart
  lib/ui/view/profile/profile_user_info_view.dart
  lib/ui/view/video/multi_video_play_view.dart
  lib/ui/view/video/share_video_play_view.dart
  lib/ui/view/video/share_video_user_info_view.dart
  lib/ui/view/video/video_user_info_view.dart
  lib/ui/widget/video/like_button_widget.dart
  lib/ui/widget/video/video_upload_dialog.dart
Labels: refactor

#123 [feat] dotenv (HH-450)
  .gitignore
  lib/data/remote/provider/kakao_login_provider.dart
  lib/main.dart
  pubspec.lock
  pubspec.yaml
Labels: feat

#124 [feat] terminated 상태일 때 push notification 처리 (HH-445)
  lib/config/fcm/remote_notifications_ervice.dart
  lib/ui/view/video/multi_video_play_view.dart
Labels: feat, fix

#125 [feat] 스테이지 에러 구독 성공 (HH-459)
  lib/config/api_url.dart
  lib/data/remote/provider/socket_stage_error_provider_impl.dart
  lib/domain/provider/socket_stage_error_provider.dart
  lib/main.dart
  lib/ui/screen/stage/popo_stage_screen.dart
  lib/ui/view/stage/popo_wait_view.dart
  pubspec.lock
Labels: feat
