Repository 2023-HATCH/hatch-flutter-app-2023, pull requests merged in 2023-07, with the labels that each got.

#32 [ui] 스테이지 실시간 채팅 바 ui 생성(HH-234)
  lib/ui/screen/popo_stage_screen.dart
  lib/ui/view/ml_kit_camera_view.dart
  lib/ui/widget/stage/stage_live_chat_widget.dart
Labels: feat, ui

#33 [ui] 스테이지 실시간 채팅 목록 ui 생성 (HH-239)
  lib/ui/screen/popo_stage_screen.dart
  lib/ui/view/popo_catch_view.dart
  lib/ui/view/popo_wait_view.dart
  lib/ui/widget/stage/stage_live_chat_bar_widget.dart
  lib/ui/widget/stage/stage_live_chat_list.widget.dart
Labels: bug, ui

#34 [ui] 스테이지 플레이 화면에 3명 스켈레톤 출력 + 캐치 버튼 ui 수정 (HH-240)
  lib/config/app_color.dart
  lib/ui/screen/popo_stage_screen.dart
  lib/ui/view/ml_kit_camera_view.dart
  lib/ui/view/popo_catch_view.dart
  lib/ui/view/popo_play_view.dart
  lib/ui/view/popo_result_view.dart
  pubspec.lock
  pubspec.yaml
Labels: ui

#35 [ui] 홈 화면: 업로드 버튼 바텀 시트 ui 개발 (HH-244)
  assets/icons/ic_home_upload_camera.svg
  assets/icons/ic_home_upload_gallery.svg
  lib/config/app_color.dart
  lib/ui/screen/home_screen.dart
  lib/ui/widget/upload_button_widget.dart
Labels: ui

#38 [feat] 스켈레톤 파일화 코드 추가 및 권한 설정 코드 추가 (HH-249)
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  ios/Runner/Info.plist
  lib/config/audio_player/audio_player_util.dart
  lib/ui/screen/on_boarding_screen.dart
  lib/ui/view/popo_play_view.dart
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: feat, ui

#40 [ui] 홈 스크린 공유하기 바텀 시트 개발 (HH-176)
  assets/icons/ic_home_share_kakao.svg
  assets/icons/ic_home_share_link.svg
  lib/ui/widget/home/home_video_frame_right_widget.dart
  lib/ui/widget/home/share_button_widget.dart
  pubspec.lock
Labels: ui

#41 [ui] 홈 스크린의 댓글 ui 개발 (HH-176)
  assets/images/chat_user_1.png
  assets/images/chat_user_2.png
  assets/images/chat_user_3.png
  assets/images/chat_user_4.png
  assets/images/chat_user_5.png
  assets/images/chat_user_6.png
  lib/ui/screen/home_screen.dart
  lib/ui/screen/main_screen.dart
  lib/ui/widget/home/chat_button_widget.dart
  lib/ui/widget/home/home_video_frame_right_widget.dart
Labels: ui

#42 [feat] 스테이지 플레이 화면 스켈레톤 색 3개로 변경 (HH-252)
  lib/config/app_color.dart
  lib/config/ml_kit/custom_pose_painter.dart
  lib/ui/view/ml_kit_camera_view.dart
  lib/ui/view/popo_play_view.dart
  lib/ui/view/popo_result_view.dart
Labels: feat

#43 [UI] 프로필 화면의 편집, 설정 페이지 UI 개발 (HH-218) / [BUG] 댓글 화면의 '게시' 버튼 색 변경 안되는 오류 해결 (HH-176)
  assets/icons/ic_back.png
  assets/icons/ic_back.svg
  assets/icons/ic_profile_edit_instagram.png
  assets/icons/ic_profile_edit_twitter.png
  assets/icons/ic_profile_edit_warning.svg
  assets/icons/ic_profile_setting_logout.svg
  assets/icons/ic_profile_setting_next.png
  assets/icons/ic_profile_setting_privacy_greement.svg
  assets/icons/ic_profile_setting_withdrawal.svg
  lib/config/app_color.dart
  lib/ui/screen/home_screen.dart
  lib/ui/screen/profile/profile_edit_screen.dart
  lib/ui/screen/profile/profile_screen.dart
  lib/ui/screen/profile/profile_setting_screen.dart
  lib/ui/widget/home/chat_button_widget.dart
  lib/ui/widget/profile/custom_simple_dialog.dart
Labels: bug, ui

#44 [fix] 스테이지 폰트 적용 및 폰트 크기 수정 (HH-256)
  lib/ui/screen/popo_stage_screen.dart
  lib/ui/view/popo_play_view.dart
  lib/ui/view/popo_result_view.dart
Labels: bug

#45 [UI] 여러 버전의 Video 화면 UI 개발 (HH-176)
  assets/icons/ic_profile_heart.svg
  assets/icons/ic_profile_trash.svg
  assets/icons/ic_profile_views.svg
  lib/ui/screen/home_screen.dart
  lib/ui/screen/profile/profile_screen.dart
  lib/ui/video_view/video_right_frame.dart
  lib/ui/video_viewer/screen/video_my_screen.dart
  lib/ui/video_viewer/screen/video_someone_screen.dart
  lib/ui/video_viewer/video_right_frame.dart
  lib/ui/video_viewer/video_user_info_frame.dart
  lib/ui/video_viewer/video_view.dart
  lib/ui/video_viewer/widget/chat_button_widget.dart
  lib/ui/video_viewer/widget/like_button_widget.dart
  lib/ui/video_viewer/widget/share_button_widget.dart
  lib/ui/widget/home/chat_button_widget.dart
  lib/ui/widget/home/home_video_frame_content_widget.dart
  lib/ui/widget/home/home_video_frame_right_widget.dart
Labels: ui, refactor

#46 [refactor] Video View 조금 더 리펙토링 (HH-176)
  lib/ui/video_view/video_right_frame.dart
  lib/ui/video_viewer/video_view.dart
Labels: refactor

#48 [ui] 업로드 화면 미리보기 영상 비율 맞추도록 ui 수정 (HH-260)
  lib/ui/screen/upload_screen.dart
  lib/ui/widget/upload/upload_tag_text_field_widget.dart
Labels: ui

#49 [bug] 프로필에서 팔로워, 팔로잉 페이지 이동시 탭 선택 버그 수정 (HH-218)
  lib/ui/screen/profile/profile_follow_screen.dart
  lib/ui/widget/profile/profile_user_info_widget.dart
Labels: bug

#50 [ui] 채팅 목록 ui 개발 (HH-261)
  assets/icons/ic_home_chat_list.svg
  assets/images/charactor_popo_default.png
  lib/config/app_color.dart
  lib/data/entity/response/chat_list_response.dart
  lib/data/entity/response/chat_list_response.g.dart
  lib/domain/entity/chat_list_item.dart
  lib/domain/entity/chat_list_item.g.dart
  lib/domain/entity/chat_user_list_item.dart
  lib/domain/entity/chat_user_list_item.g.dart
  lib/ui/screen/chat_detail_screen.dart
  lib/ui/screen/chat_list_screen.dart
  lib/ui/screen/home_screen.dart
  lib/ui/widget/chat/chat_list_item_widget.dart
Labels: ui

#51 [UI] 홈 화면의 검색 페이지 UI 개발 (HH-176)
  lib/config/app_color.dart
  lib/data/local/provider/video_play_provider.dart
  lib/ui/screen/home/home_screen.dart
  lib/ui/screen/home/home_search_screen.dart
  lib/ui/screen/main_screen.dart
  lib/ui/screen/profile/profile_screen.dart
  pubspec.lock
  pubspec.yaml
Labels: feat, ui

#52 [Bug] #45에서 발견한 채팅 및 비디오 화면 오류 해결 (HH-176/HH-218)
  lib/ui/video_viewer/screen/video_my_screen.dart
  lib/ui/video_viewer/screen/video_someone_screen.dart
  lib/ui/video_viewer/widget/chat_button_widget.dart
Labels: bug

#53 [ui] 채팅 상세 ui 개발 + (스테이지 채팅 목록 경계선 흐리게 + 업로드 TextField border width 줄이기) (HH-264)
  assets/images/charactor_popo_default.png
  lib/config/app_color.dart
  lib/data/entity/response/chat_detail_list_response.dart
  lib/data/entity/response/chat_detail_list_response.g.dart
  lib/domain/entity/chat_detail_list_item.dart
  lib/domain/entity/chat_detail_list_item.g.dart
  lib/ui/screen/chat_detail_screen.dart
  lib/ui/screen/upload_screen.dart
  lib/ui/widget/chat/chat_detail_left_bubble_widget.dart
  lib/ui/widget/chat/chat_detail_right_bubble_widget.dart
  lib/ui/widget/chat/chat_list_item_widget.dart
  lib/ui/widget/stage/stage_live_chat_list.widget.dart
  lib/ui/widget/upload/upload_tag_text_field_widget.dart
Labels: ui

#54 [feat] 스테이지 채팅 목록 조회 api 연결 (HH-278)
  lib/config/api_url.dart
  lib/data/entity/base_object.dart
  lib/data/entity/base_response.dart
  lib/data/entity/request/stage_talk_message_request.dart
  lib/data/entity/request/stage_talk_message_request.g.dart
  lib/data/entity/response/stage_talk_message_response.dart
  lib/data/entity/response/stage_talk_message_response.g.dart
  lib/data/remote/provider/stage_talk_provider_impl.dart
  lib/domain/entity/stage_talk_list_item.dart
  lib/domain/entity/stage_talk_list_item.g.dart
  lib/domain/provider/stage_talk_provider.dart
  lib/ui/widget/stage/stage_live_chat_list.widget.dart
  lib/ui/widget/stage/talk_list_item_widget.dart
Labels: feat

#55 [feat] 영상 업로드 api 연결 (HH-276)
  lib/config/api_url.dart
  lib/data/entity/request/video_upload_request.dart
  lib/data/entity/request/video_upload_request.g.dart
  lib/data/entity/response/video_upload_response.dart
  lib/data/entity/response/video_upload_response.g.dart
  lib/data/remote/provider/stage_talk_provider_impl.dart
  lib/data/remote/provider/video_upload_provider_impl.dart
  lib/domain/provider/video_upload_provider.dart
  lib/ui/screen/upload_screen.dart
Labels: feat

#56 [feat] 스테이지 사용자 목록 api 연결 (HH-281)
  lib/config/api_url.dart
  lib/data/entity/response/stage_user_list_response.dart
  lib/data/entity/response/stage_user_list_response.g.dart
  lib/data/remote/provider/stage_provider_impl.dart
  lib/domain/entity/stage_user_list_item.dart
  lib/domain/entity/stage_user_list_item.g.dart
  lib/domain/provider/stage_provider.dart
  lib/ui/screen/popo_stage_screen.dart
  lib/ui/widget/stage/talk_list_item_widget.dart
Labels: feat

#57 [feat] 스테이지 소켓 연결, 구독 api 연결 및 대기>캐치>플레이>결과 루틴 반복 (HH-280)
  lib/config/api_url.dart
  lib/data/entity/base_socket_response.dart
  lib/ui/screen/main_screen.dart
  lib/ui/screen/popo_stage_screen.dart
  lib/ui/view/ml_kit_camera_view.dart
  lib/ui/view/popo_catch_view.dart
  lib/ui/view/popo_play_view.dart
  lib/ui/view/popo_result_view.dart
  lib/ui/widget/stage/stage_live_chat_bar_widget.dart
  pubspec.lock
  pubspec.yaml
Labels: feat

#58 [feat] 스테이지 입장/퇴장 api 연결 (HH-285)
  lib/config/api_url.dart
  lib/data/entity/base_response.dart
  lib/data/entity/base_socket_response.dart
  lib/data/entity/request/stage_enter_request.dart
  lib/data/entity/request/stage_enter_request.g.dart
  lib/data/entity/response/stage_enter_response.dart
  lib/data/entity/response/stage_enter_response.g.dart
  lib/data/entity/socket_response/user_count_response.dart
  lib/data/entity/socket_response/user_count_response.g.dart
  lib/data/remote/provider/stage_provider_impl.dart
  lib/domain/provider/stage_provider.dart
  lib/ui/screen/popo_stage_screen.dart
Labels: feat
