Repository 2023-HATCH/hatch-flutter-app-2023, pull requests merged in 2023-08, with the labels that each got.

#61 [feat] 스테이지 실시간 반응 전송 소켓 연결 (HH-287)
  lib/config/api_url.dart
  lib/data/remote/provider/stage_provider_impl.dart
  lib/ui/screen/popo_stage_screen.dart
  lib/ui/widget/stage/stage_live_chat_bar_widget.dart
Labels: feat

#62 [feat] 스테이지 사용자 목록 다이얼로그 실시간 변동사항 반영 (HH-288)
  lib/data/remote/provider/stage_provider_impl.dart
  lib/ui/screen/popo_stage_screen.dart
Labels: feat

#64 [bug] #63 홈 새로고침 후 발생하는 dispose 오류 해결 (HH-274)
  lib/data/local/provider/video_play_provider.dart
  lib/ui/video_viewer/video_view.dart
Labels: bug

#66 [feat] 좋아요 등록 api, 좋아요 삭제 api 연결 (HH-300)
  lib/config/api_url.dart
  lib/data/remote/provider/kakao_login_provider.dart
  lib/data/remote/provider/like_provider.dart
  lib/data/remote/repository/home_repository.dart
  lib/data/remote/repository/like_repository.dart
  lib/domain/entity/video_data.dart
  lib/domain/entity/video_data.g.dart
  lib/main.dart
  lib/ui/screen/main_screen.dart
  lib/ui/video_viewer/widget/like_button_widget.dart
Labels: feat

#67 [feat] 댓글 목록 조회 api, 댓글 등록 api, 댓글 삭제 api 연결 (HH-305)
  lib/config/api_url.dart
  lib/data/entity/response/comment_list_response.dart
  lib/data/entity/response/comment_list_response.g.dart
  lib/data/local/provider/video_play_provider.dart
  lib/data/remote/provider/comment_provider.dart
  lib/data/remote/provider/kakao_login_provider.dart
  lib/data/remote/repository/comment_repository.dart
  lib/data/remote/repository/home_repository.dart
  lib/data/remote/repository/kakao_login_repository.dart
  lib/data/remote/repository/like_repository.dart
  lib/domain/entity/comment_data.dart
  lib/domain/entity/comment_data.g.dart
  lib/domain/entity/user_data.dart
  lib/domain/entity/user_data.g.dart
  lib/domain/entity/video_data.dart
  lib/main.dart
  lib/ui/screen/profile/profile_screen.dart
  lib/ui/screen/profile/profile_setting_screen.dart
  lib/ui/video_viewer/screen/video_someone_screen.dart
  lib/ui/video_viewer/video_right_frame.dart
  lib/ui/video_viewer/video_user_info_frame.dart
  lib/ui/video_viewer/video_view.dart
  lib/ui/video_viewer/widget/chat_button_widget.dart
  lib/ui/video_viewer/widget/comment_button_widget.dart
  lib/ui/video_viewer/widget/like_button_widget.dart
  lib/ui/widget/profile/profile_user_info_widget.dart
Labels: feat, bug

#68 [feat] 스테이지 플레이 시 스켈레톤 실시간 송출 기능 추가(HH-291)
  lib/config/api_url.dart
  lib/data/entity/base_socket_response.dart
  lib/data/entity/socket_request/send_skeleton_request.dart
  lib/data/entity/socket_response/send_skeleton_response.dart
  lib/data/remote/provider/socket_stage_provider_impl.dart
  lib/data/remote/provider/stage_provider_impl.dart
  lib/domain/entity/stage_skeleton_pose_landmark.dart
  lib/domain/provider/socket_stage_provider.dart
  lib/main.dart
  lib/ui/screen/home/home_screen.dart
  lib/ui/screen/main_screen.dart
  lib/ui/screen/popo_stage_screen.dart
  lib/ui/screen/profile/profile_screen.dart
  lib/ui/view/ml_kit_camera_view.dart
  lib/ui/view/popo_play_view.dart
  lib/ui/view/popo_result_view.dart
  lib/ui/widget/home/upload_button_widget.dart
  lib/ui/widget/stage/stage_live_chat_bar_widget.dart
  lib/ui/widget/stage/stage_live_talk_list_widget.dart
Labels: feat

#69 [feat] 영상 삭제 api 연결 (HH-323)
  lib/config/api_url.dart
  lib/data/entity/request/home_videos_request.dart
  lib/data/entity/request/videos_request.dart
  lib/data/entity/request/videos_request.g.dart
  lib/data/entity/response/home_videos_response.dart
  lib/data/entity/response/videos_response.dart
  lib/data/entity/response/videos_response.g.dart
  lib/data/remote/provider/home_provider.dart
  lib/data/remote/provider/video_provider.dart
  lib/data/remote/repository/comment_repository.dart
  lib/data/remote/repository/video_repository.dart
  lib/main.dart
  lib/ui/video_viewer/screen/video_my_screen.dart
  lib/ui/video_viewer/video_view.dart
Labels: feat

#70 [feat] 로컬에 저장된 토큰을 불러오는 코드 단순화 & 토큰 갱신 로직 개발 (HH-221)
  lib/data/remote/provider/kakao_login_provider.dart
  lib/data/remote/repository/comment_repository.dart
  lib/data/remote/repository/kakao_login_repository.dart
  lib/data/remote/repository/like_repository.dart
  lib/data/remote/repository/video_repository.dart
Labels: feat, refactor

#71 [Bug] 댓글창의 삭제 버튼 글쓴이만 볼 수 있게 수정 & 댓글창의 날짜 및 시간 2자로 통일되게 수정 (HH-274)
  lib/ui/video_viewer/widget/comment_button_widget.dart
Labels: bug, ui

#72 [bug][ui] 댓글창 overflow 해결, 이모티콘바 ui 변경 (HH-274)
  lib/ui/video_viewer/widget/comment_button_widget.dart
Labels: bug, ui

#73 [ui] 댓글창 UI 전면 수정 (HH-274)
  lib/ui/video_viewer/widget/comment_button_widget.dart
Labels: design, ui

#74 [feat] 스테이지 MVP 스켈레톤 소켓에 전송/응답 처리 (HH-325)
  lib/config/api_url.dart
  lib/data/entity/socket_request/send_skeleton_request.dart
  lib/data/entity/socket_response/send_skeleton_response.dart
  lib/data/entity/socket_response/stage_mvp_response.dart
  lib/data/entity/socket_response/stage_mvp_response.g.dart
  lib/data/remote/provider/socket_stage_provider_impl.dart
  lib/domain/provider/socket_stage_provider.dart
  lib/ui/screen/popo_stage_screen.dart
  lib/ui/view/popo_catch_view.dart
  lib/ui/view/popo_play_view.dart
  lib/ui/view/popo_result_view.dart
  lib/ui/widget/stage/stage_live_chat_bar_widget.dart
Labels: feat

#75 [feat] 캐치 사운드, 플레이 대기 카운트다운 사운드 추가 및 스켈레톤 잔상 제거 (HH-333)
  assets/audios/sound_catch_click.mp3
  assets/audios/sound_play_wait.mp3
  lib/data/remote/provider/socket_stage_provider_impl.dart
  lib/ui/view/ml_kit_camera_view.dart
  lib/ui/view/popo_catch_view.dart
  lib/ui/view/popo_play_view.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
Labels: feat

#76 [bug][feat] 홈, 프로필 UI 수정(HH-218)
  lib/ui/screen/profile/profile_screen.dart
  lib/ui/video_viewer/video_view.dart
  lib/ui/video_viewer/widget/comment_button_widget.dart
  lib/ui/widget/login_modal_content_widget.dart
  lib/ui/widget/profile/profile_user_info_widget.dart
Labels: feat, bug, ui

#77 [feat] 스테이지 중간 입장 (HH-337)
  lib/config/api_url.dart
  lib/config/audio_player/audio_player_util.dart
  lib/data/entity/response/stage_enter_response.dart
  lib/data/entity/response/stage_enter_response.g.dart
  lib/data/entity/socket_response/catch_start_response.dart
  lib/data/entity/socket_response/catch_start_response.g.dart
  lib/data/remote/provider/socket_stage_provider_impl.dart
  lib/data/remote/provider/stage_provider_impl.dart
  lib/domain/entity/stage_music_data.dart
  lib/domain/entity/stage_music_data.g.dart
  lib/domain/provider/socket_stage_provider.dart
  lib/domain/provider/stage_provider.dart
  lib/ui/screen/popo_stage_screen.dart
  lib/ui/view/ml_kit_camera_view.dart
  lib/ui/view/popo_catch_view.dart
  lib/ui/view/popo_play_view.dart
  lib/ui/view/popo_result_view.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
Labels: feat

#78 [feat] 스테이지 캐치, 결과 화면 중간입장 처리(HH-339)
  lib/config/audio_player/audio_player_util.dart
  lib/data/remote/provider/socket_stage_provider_impl.dart
  lib/ui/screen/popo_stage_screen.dart
  lib/ui/view/ml_kit_camera_view.dart
  lib/ui/view/popo_catch_view.dart
Labels: feat

#79 [bug] 홈 영상 조회 속도 향상 및 오류 해결 V2 (HH-274)
  lib/data/local/provider/multi_video_play_provider.dart
  lib/data/remote/provider/kakao_login_provider.dart
  lib/domain/entity/video_data.dart
  lib/domain/entity/video_data.g.dart
  lib/main.dart
  lib/ui/screen/chat/chat_list_screen.dart
  lib/ui/screen/home/home_screen.dart
  lib/ui/screen/home/home_search_screen.dart
  lib/ui/screen/home/home_upload_screen.dart
  lib/ui/screen/main_screen.dart
  lib/ui/screen/on_boarding_screen.dart
  lib/ui/screen/popo_stage_screen.dart
  lib/ui/screen/profile/profile_follow_screen.dart
  lib/ui/screen/profile/profile_setting_screen.dart
  lib/ui/video_viewer/screen/video_my_screen.dart
  lib/ui/video_viewer/screen/video_someone_screen.dart
  lib/ui/video_viewer/video_right_frame.dart
  lib/ui/video_viewer/video_user_info_frame.dart
  lib/ui/video_viewer/video_view.dart
  lib/ui/video_viewer/widget/comment_button_widget.dart
  lib/ui/video_viewer/widget/like_button_widget.dart
  lib/ui/widget/home/upload_button_widget.dart
Labels: feat, bug

#81 [bug] #76 홈, 프로필 UI 오류 해결 (HH-274)
  lib/config/app_color.dart
  lib/ui/screen/profile/profile_screen.dart
  lib/ui/video_viewer/video_view.dart
  lib/ui/video_viewer/widget/comment_button_widget.dart
  lib/ui/widget/profile/profile_user_info_widget.dart
Labels: feat, bug

#82 [feat] 조회수 등록 api 연결 (HH-346)
  lib/data/local/provider/multi_video_play_provider.dart
  lib/data/remote/provider/video_provider.dart
  lib/data/remote/repository/video_repository.dart
  lib/ui/screen/main_screen.dart
Labels: feat

#83 [feat] 프로필 api 연결 1차 개발 - 사용자 정보, 프로필 수정, 업로드 영상, 좋아요한 영상 조회 api(HH-323)
  assets/icons/ic_profile_follow.svg
  assets/icons/ic_profile_twitter.svg
  assets/icons/ic_profile_unfollow.svg
  lib/config/api_url.dart
  lib/data/entity/request/profile_edit_request.dart
  lib/data/entity/request/profile_edit_request.g.dart
  lib/data/entity/request/profile_videos_request.dart
  lib/data/entity/request/profile_videos_request.g.dart
  lib/data/entity/response/profile_response.dart
  lib/data/entity/response/profile_response.g.dart
  lib/data/remote/provider/kakao_login_provider.dart
  lib/data/remote/provider/profile_provider.dart
  lib/data/remote/provider/video_provider.dart
  lib/data/remote/repository/profile_repository.dart
  lib/domain/entity/profile_data.dart
  lib/domain/entity/profile_data.g.dart
  lib/main.dart
  lib/ui/screen/home/home_screen.dart
  lib/ui/screen/home/home_search_screen.dart
  lib/ui/screen/main_screen.dart
  lib/ui/screen/profile/profile_edit_screen.dart
  lib/ui/screen/profile/profile_screen.dart
  lib/ui/video_viewer/multi_video_player_view.dart
  lib/ui/video_viewer/screen/profile_video_screen.dart
  lib/ui/video_viewer/screen/video_my_screen.dart
  lib/ui/video_viewer/screen/video_someone_screen.dart
  lib/ui/video_viewer/video_user_info_frame.dart
  lib/ui/video_viewer/widget/profile_tab_videos_widget.dart
  lib/ui/video_viewer/widget/profile_tapbar_widget.dart
  lib/ui/video_viewer/widget/profile_video_skeleton_loader_widget.dart
  lib/ui/video_viewer/widget/video_player_widget.dart
  lib/ui/widget/profile/profile_buttons_widget.dart
  lib/ui/widget/profile/profile_user_info_widget.dart
  pubspec.lock
  pubspec.yaml
Labels: feat, refactor

#85 [feat] 채팅, 스테이지 페이지네이션 (HH-352)
  assets/icons/ic_home_comment.svg
  lib/data/remote/provider/chat_provider_impl.dart
  lib/data/remote/provider/socket_stage_provider_impl.dart
  lib/data/remote/provider/stage_talk_provider_impl.dart
  lib/domain/provider/chat_provider.dart
  lib/main.dart
  lib/ui/screen/chat/chat_detail_screen.dart
  lib/ui/screen/chat/chat_room_list_screen.dart
  lib/ui/video_viewer/video_right_frame.dart
  lib/ui/view/ml_kit_camera_view.dart
  lib/ui/view/popo_play_view.dart
  lib/ui/view/popo_result_view.dart
  lib/ui/widget/chat/chat_detail_left_bubble_widget.dart
  lib/ui/widget/chat/chat_room_list_item_widget.dart
  lib/ui/widget/stage/stage_live_talk_list_widget.dart
Labels: feat, ui

#86 [feat/fix] 채팅 날짜 헤더 추가 및 스테이지 소켓 오류 해결(HH-355)
  lib/config/app_color.dart
  lib/data/remote/provider/socket_stage_provider_impl.dart
  lib/domain/provider/socket_stage_provider.dart
  lib/ui/screen/chat/chat_detail_screen.dart
  lib/ui/screen/popo_stage_screen.dart
  lib/ui/view/ml_kit_camera_view.dart
  lib/ui/view/popo_catch_view.dart
  lib/ui/widget/chat/chat_detail_left_bubble_widget.dart
  lib/ui/widget/chat/chat_detail_right_bubble_widget.dart
Labels: feat, fix

#87 [rename] 서버 연결용 provider를 repository로 이름 변경 (HH-358)
  lib/data/remote/provider/chat_provider_impl.dart
  lib/data/remote/provider/popo_skeleton_provider_impl.dart
  lib/data/remote/provider/socket_stage_provider_impl.dart
  lib/data/remote/provider/stage_provider_impl.dart
  lib/data/remote/provider/stage_talk_provider_impl.dart
  lib/data/remote/provider/video_upload_provider_impl.dart
  lib/data/remote/repository/chat_repository_impl.dart
  lib/data/remote/repository/stage_repository_impl.dart
  lib/data/remote/repository/stage_talk_repository_impl.dart
  lib/data/remote/repository/video_upload_repository_impl.dart
  lib/domain/provider/popo_skeleton_provider.dart
  lib/domain/repository/chat_repository.dart
  lib/domain/repository/stage_repository.dart
  lib/domain/repository/stage_talk_repository.dart
  lib/domain/repository/video_upload_repository.dart
Labels: rename

#88 [feat] 프로필 api 연결 2차 개발 - 프로필의 영상, 프로필 팔로우(등록, 삭제, 조회) 기능 개발 (HH-323)
  android/app/src/main/AndroidManifest.xml
  lib/config/api_url.dart
  lib/data/entity/response/follow_list_response.dart
  lib/data/entity/response/follow_list_response.g.dart
  lib/data/local/provider/multi_video_play_provider.dart
  lib/data/remote/provider/follow_provider.dart
  lib/data/remote/provider/kakao_login_provider.dart
  lib/data/remote/provider/profile_provider.dart
  lib/data/remote/provider/video_provider.dart
  lib/data/remote/repository/follow_repository.dart
  lib/data/remote/repository/profile_repository.dart
  lib/domain/entity/follow_data.dart
  lib/domain/entity/follow_data.g.dart
  lib/domain/entity/profile_data.dart
  lib/domain/entity/profile_data.g.dart
  lib/domain/entity/video_data.dart
  lib/domain/entity/video_data.g.dart
  lib/main.dart
  lib/ui/screen/chat/chat_room_list_screen.dart
  lib/ui/screen/home/home_screen.dart
  lib/ui/screen/home/home_search_screen.dart
  lib/ui/screen/home/home_upload_screen.dart
  lib/ui/screen/main_screen.dart
  lib/ui/screen/popo_stage_screen.dart
  lib/ui/screen/profile/profile_follow_screen.dart
  lib/ui/screen/profile/profile_screen.dart
  lib/ui/screen/profile/profile_setting_screen.dart
  lib/ui/video_viewer/multi_video_player_view.dart
  lib/ui/video_viewer/screen/profile_video_screen.dart
  lib/ui/video_viewer/video_right_frame.dart
  lib/ui/video_viewer/video_user_info_frame.dart
  lib/ui/video_viewer/widget/comment_button_widget.dart
  lib/ui/video_viewer/widget/like_button_widget.dart
  lib/ui/video_viewer/widget/profile_tab_videos_widget.dart
  lib/ui/video_viewer/widget/profile_video_skeleton_loader_widget.dart
  lib/ui/video_viewer/widget/video_player_widget.dart
  lib/ui/widget/home/upload_button_widget.dart
  lib/ui/widget/profile/profile_buttons_widget.dart
  lib/ui/widget/profile/profile_user_info_widget.dart
  pubspec.lock
  pubspec.yaml
Labels: feat

#89 [feat] 검색 api 연결 (HH-365)
  lib/config/api_url.dart
  lib/data/local/provider/multi_video_play_provider.dart
  lib/data/remote/provider/search_provider.dart
  lib/data/remote/repository/search_repository.dart
  lib/main.dart
  lib/ui/frame/profile/profile_buttons_frame.dart
  lib/ui/frame/video/video_right_frame.dart
  lib/ui/frame/video/video_user_info_frame.dart
  lib/ui/frame/video_right_frame.dart
  lib/ui/loader/music_spinner_loader.dart
  lib/ui/loader/profile_video_skeleton_loader.dart
  lib/ui/loader/search_textfield_loader.dart
  lib/ui/loader/user_list_loader.dart
  lib/ui/screen/home/home_screen.dart
  lib/ui/screen/home/home_search_screen.dart
  lib/ui/screen/profile/follow_tab_screen.dart
  lib/ui/screen/profile/profile_screen.dart
  lib/ui/screen/profile/profile_setting_screen.dart
  lib/ui/screen/profile/profile_video_detail_screen.dart
  lib/ui/view/home/comment_button_view.dart
  lib/ui/view/home/search_detail_view.dart
  lib/ui/view/home/search_view.dart
  lib/ui/view/home/user_list_view.dart
  lib/ui/view/profile/follow_user_list_view.dart
  lib/ui/view/profile/profile_tab_videos_view.dart
  lib/ui/view/profile/profile_user_info_widget.dart
  lib/ui/view/video/multi_video_player_view.dart
  lib/ui/widget/custom_simple_dialog_widget.dart
  lib/ui/widget/home/search_textfield_widget.dart
  lib/ui/widget/profile/profile_tapbar_widget.dart
  lib/ui/widget/video/like_button_widget.dart
  lib/ui/widget/video/share_button_widget.dart
  lib/ui/widget/video/video_player_widget.dart
  pubspec.lock
Labels: feat, refactor

#92 [feat] 계정 검색에 자기소개 추가 (HH-365)
  lib/data/remote/provider/search_provider.dart
  lib/data/remote/repository/search_repository.dart
  lib/domain/entity/search_user_data.dart
  lib/domain/entity/search_user_data.g.dart
  lib/ui/view/home/search_detail_view.dart
  lib/ui/view/home/user_list_view.dart
  lib/ui/widget/home/search_textfield_widget.dart
Labels: feat, ui

#93 [Feat] 페이지 이동 간 애니메이션 추가 (HH-388)
  lib/ui/frame/video/video_right_frame.dart
  lib/ui/screen/home/home_screen.dart
  lib/ui/screen/main_screen.dart
  lib/ui/screen/profile/profile_screen.dart
  lib/ui/view/home/search_view.dart
  lib/ui/view/profile/profile_buttons_view.dart
  lib/ui/view/profile/profile_tab_videos_view.dart
  lib/ui/view/profile/profile_user_info_view.dart
  lib/ui/view/video/video_right_view.dart
  lib/ui/view/video/video_user_info_view.dart
  lib/ui/widget/page_route_with_animation.dart
  lib/ui/widget/profile/profile_tapbar_widget.dart
  lib/ui/widget/video/video_player_widget.dart
Labels: feat

#94 [feat] 파이어베이스 연동 (HH-391)
  android/app/build.gradle
  android/app/google-services.json
  android/build.gradle
  ios/Runner/GoogleService-Info.plist
  ios/firebase_app_id_file.json
  lib/firebase_options.dart
  lib/main.dart
  linux/flutter/generated_plugin_registrant.cc
  linux/flutter/generated_plugins.cmake
  macos/Flutter/GeneratedPluginRegistrant.swift
  macos/firebase_app_id_file.json
  pubspec.lock
  pubspec.yaml
  windows/flutter/generated_plugin_registrant.cc
  windows/flutter/generated_plugins.cmake
Labels: feat

#95 [feat] 프로필 화면에서 채팅방 생성 기능 추가(HH-391)
  lib/main.dart
  lib/ui/view/profile/profile_buttons_view.dart
  lib/ui/widget/chat/chat_room_list_item_widget.dart
Labels: feat

#96 [feat] 로그인 로그아웃시 푸시 알림을 위한 FCM 토큰 처리 (HH-390)
  android/app/build.gradle
  android/app/src/main/AndroidManifest.xml
  lib/config/api_url.dart
  lib/data/remote/provider/kakao_login_provider.dart
  lib/data/remote/repository/kakao_login_repository.dart
  macos/Flutter/GeneratedPluginRegistrant.swift
  pubspec.lock
  pubspec.yaml
Labels: feat

#97 [feat] 버튼 패딩 추가, 애니메이션 적용, 아이콘 변경 (HH-388)
  lib/ui/screen/home/home_screen.dart
  lib/ui/screen/home/home_search_screen.dart
  lib/ui/screen/main_screen.dart
  lib/ui/screen/profile/follow_tab_screen.dart
  lib/ui/screen/profile/profile_edit_screen.dart
  lib/ui/screen/profile/profile_setting_screen.dart
  lib/ui/widget/profile/profile_tapbar_widget.dart
Labels: feat

#98 [feat] 좋아요, 댓글, 공유 아이콘에 패딩 추가, [fix] 자기소개를 nullable로 수정 (HH-388)
  lib/data/remote/repository/search_repository.dart
  lib/domain/entity/search_user_data.dart
  lib/domain/entity/search_user_data.g.dart
  lib/ui/loader/user_list_loader.dart
  lib/ui/view/home/user_list_view.dart
  lib/ui/view/video/video_right_view.dart
Labels: feat, fix

#99 [feat] 화면 로더 추가 (HH-388)
  assets/images/dance_popo_left.svg
  assets/images/dance_popo_right.svg
  lib/ui/loader/upload_spinner_loader.dart
  lib/ui/screen/home/home_search_screen.dart
  lib/ui/screen/home/home_upload_screen.dart
  lib/ui/screen/profile/follow_tab_screen.dart
  lib/ui/screen/profile/profile_screen.dart
  lib/ui/screen/profile/profile_setting_screen.dart
Labels: feat, ui

#100 [feat] 링크 공유 기능 개발 (HH-360)
  android/app/src/main/AndroidManifest.xml
  ios/Runner/Runner.entitlements
  lib/config/firebase/dynamic_link.dart
  lib/config/firebase/dynamic_link_util.dart
  lib/config/firebase/i_dynamic_link.dart
  lib/data/remote/provider/socket_stage_provider_impl.dart
  lib/main.dart
  lib/ui/screen/share_screen.dart
  lib/ui/view/stage/ml_kit_camera_view.dart
  lib/ui/view/stage/popo_catch_view.dart
  lib/ui/view/stage/popo_play_view.dart
  lib/ui/view/stage/popo_result_view.dart
  lib/ui/view/stage/popo_wait_view.dart
  lib/ui/view/video/video_right_view.dart
  lib/ui/widget/video/share_button_widget.dart
  pubspec.lock
  pubspec.yaml
Labels: feat

#101 [feat/ui] 스테이지 결과 화면 음악 연결 및 ui 변경 (HH-396)
  assets/icons/ic_countdown_1.png
  assets/icons/ic_countdown_2.png
  assets/icons/ic_countdown_3.png
  assets/icons/ic_countdown_4.png
  assets/icons/ic_countdown_5.png
  lib/data/remote/provider/socket_stage_provider_impl.dart
  lib/data/remote/provider/stage_provider_impl.dart
  lib/ui/screen/main_screen.dart
  lib/ui/view/stage/ml_kit_camera_view.dart
  lib/ui/view/stage/popo_catch_view.dart
  lib/ui/view/stage/popo_play_view.dart
Labels: feat, ui

#102 [feat] 채팅 사용자 검색 기능 개발 (HH-405)
  lib/config/api_url.dart
  lib/data/entity/response/chat_search_user_list_response.dart
  lib/data/entity/response/chat_search_user_list_response.g.dart
  lib/data/remote/provider/chat_provider_impl.dart
  lib/data/remote/repository/chat_repository_impl.dart
  lib/domain/entity/chat_user_list_item.dart
  lib/domain/entity/chat_user_list_item.g.dart
  lib/domain/entity/follow_data.g.dart
  lib/domain/entity/search_user_data.g.dart
  lib/domain/provider/chat_provider.dart
  lib/domain/repository/chat_repository.dart
  lib/ui/screen/chat/chat_room_list_screen.dart
  lib/ui/view/profile/profile_buttons_view.dart
  lib/ui/widget/chat/chat_detail_left_bubble_widget.dart
  lib/ui/widget/chat/chat_detail_right_bubble_widget.dart
  lib/ui/widget/chat/chat_search_user_list_item_widget.dart
  lib/ui/widget/chat/chat_search_user_textfield_widget.dart
Labels: feat
